### PR TITLE
add GoogleMapsPlacesFactory

### PR DESCRIPTION
**Pull request by bitecodes**
Add a factory for https://github.com/geocoder-php/google-maps-places-provider

### CODE REVIEW

**Comment by norkunas** [comment]
@Nyholm could you merge this?

**Comment by Nyholm** [comment]
But the tests are red. That would mean master would be red, right?

**Comment by norkunas** [comment]
Because #266 is not merged yet, but this looks good.

**Comment by norkunas** [comment]
@bitecodes could you force push to your branch to trigger travis build?

**Comment by norkunas** [comment]
Thank you @bitecodes

**Pull request merged**
