### PR TITLE
Add optional precision argument

### PR DESCRIPTION
**Pull request by samybasset**
Update for the bundle after https://github.com/geocoder-php/Geocoder/pull/883 is merged, to accept a optional precision argument.

The `geocoder-php/Geocoder` package needs to be updated after https://github.com/geocoder-php/Geocoder/pull/883 is merged.

### CODE REVIEW

**Comment by samybasset** [comment]
Thanks for the fast release! Can you also tag a new release?

**Comment by Nyholm** [comment]
Sure. Have you tested dev-master?

//Tobias Nyholm

**Comment by ruudk** [comment]
We'll test dev-master on Monday :v: Thanks for merging :)

**Comment by Nyholm** [comment]
Perfect. Ping me and I'll tag new releases.

**Comment by ruudk** [comment]
@Nyholm We tested it and it works 🎉 Can you please tag a new release?

**Pull request merged**
