### PR TITLE
Add MapboxFactory

### PR DESCRIPTION
**Pull request by cdcrft**
I needed Mapbox for a project so I thought i would contribute and add MapboxFactory for every one. 

I also added the tests and it was all fine for me.

Tell me if it requires any modification in order for this to be merged.

Regards,

### CODE REVIEW

**Comment by cdcrft** [comment]
I have not looked into the details of the tests and the whole code, but I made a mistake by writing "package-name" instead of "packageName" and the tests did all passed. 

Only when I implemented the package into my own project have I had the issue :

"Notice: Undefined index: packageName"

**Comment by norkunas** [comment]
Hello, everything looks fine. Could you squash your commits?

**Comment by cdcrft** [comment]
Hello, i'm not used to this process so I hope I did ok

**Comment by norkunas** [comment]
Looks good. One thing to notice is that your commit isn't related to your account so you won't appear in the contributors list, would you like to map it to your account or it's okay to merge this as is? :)

**Comment by cdcrft** [comment]
Oh thanks for noticing that. Could you please confirm that it's ok now ? 
I'm not sure where I have to look at.

**Comment by norkunas** [comment]
Thank you :-)

**Pull request merged**
