### PR TITLE
Add support for api-key based authentication in here factory

### PR DESCRIPTION
**Pull request by pupaxxo**

### CODE REVIEW

**Comment by norkunas** [comment]
Hello and thank you.
You should fix the CI

**Comment by pupaxxo** [comment]
@norkunas fixed :=) The PHP-cs-fixer test is failing for an error in tests/bootstrap.php file, it isn't related to the PR.

**Comment by norkunas** [comment]
Could you rebase? :)

**Comment by norkunas** [comment]
Yes, this breaks also testing on 7.2, so please revert the constraint :)

**Comment by norkunas** [comment]
Thank you :)

**Pull request merged**
