### PR TITLE
Allow Symfony 6

### PR DESCRIPTION
**Pull request by norkunas**

### CODE REVIEW

**Comment by norkunas** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6095 blocker

**Comment by ruudk** [comment]
> [FriendsOfPHP/PHP-CS-Fixer#6095](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6095) blocker

How is this a blocker? The `PHP-CS-Fixer` step fails with 
```
Warning: Found violation(s) of type: ordered_imports
```

I think you just need to fix that and it's done :)

**Comment by norkunas** [comment]
it was because sf6 was not supported along cs-fixer, I see it's merged, will update this soon

**Comment by norkunas** [comment]
Another blocker is https://github.com/php-http/curl-client which has a PR for sf6 support

**Comment by ruudk** [comment]
For reference:
- https://github.com/php-http/curl-client/pull/76

**Comment by Chris53897** [comment]
@norkunas Thanks for the PR. Now that the curl-client blocker is gone, can you please force push to rerun the tests?

**Comment by norkunas** [comment]
green&peace. at last.

@Nyholm I've currently restored to use curl client instead of mock to lower size of changes for easier review.

**Pull request merged**
