### PR TITLE
Implement PluginProvider and awesome plugin support

### LINKED ISSUE #151: Relayout the profiler page
I think it would look better to have a 4 column table. 

| idx | Query | Result | Time |
| --- | ------ | ------ | ----- |
| 1 | "Flat iron building | 2 Results (show/hide) | 200ms |
| 2 | (47, 11) | 5 Results (show/hide) | 200ms |

What do you think?

### PR DESCRIPTION
**Pull request by Nyholm**
We just need to create the PluginProvider and append the plugin to it.

Blocked by https://github.com/geocoder-php/Geocoder/pull/742

This will fix https://github.com/geocoder-php/BazingaGeocoderBundle/issues/129 and fix #151

### CODE REVIEW

**Comment by willdurand** [comment]
Ok now I see the usefulness of this plugin feature. I'm 👍

**Comment by Nyholm** [comment]
This PR is now ready for a final review

**Comment by Nyholm** [comment]
screen shot 2017-08-03 at 18 20 58

**Comment by willdurand** [comment]
❤️

**Pull request merged**
