### PR TITLE
Test doctrine in separate build

### PR DESCRIPTION
**Pull request by Nyholm**
This will allow us to test on Symfony 4. 

The "lowest-version" test fails because it picks beta1 instead of beta2 on GoogleMaps. I will be fine when we release stable versions.

Im fine with this failing for 2 weeks.

### CODE REVIEW

**Comment by willdurand** [comment]
poke @Baachi

**Comment by Baachi** [comment]
Wow really cool, love it. Is the failure related to this PR, because it seems related to the `GoogleMapsProvider`?

**Comment by Nyholm** [comment]
Thank you. I've made some major changes to the architecture of this bundle to benefit the great features of Symfony 3.3+ and PHP7. It will also work better with the multi package approach for the geocoder/providers. 

It is basically only plugin support that is missing for us to release the bundle. So I guess we release 5.0.0 in August.

The build error is because it is a "--prefer-lowest" test. So it gets the first beta release. It will be fine when we release 4.0.0 of the geocoder.

**Comment by Nyholm** [comment]
The build is green now. 

Thank you for the reviews.

**Pull request merged**
