### PR TITLE
Updated namespace to Bazinga\GeocoderBundle 

### PR DESCRIPTION
**Pull request by Nyholm**
There is no need for the extra "Bundle" in the namespace. It does also make our service names longer. 

Btw, why do we need "Bazinga" at all? Isn't this just because of historical reasons? 
@willdurand Do you want to keep it or do you want to update it to something else?
Example: `Geocoder\GeocoderBundle`?

### CODE REVIEW

**Comment by willdurand** [comment]
Could be renamed I guess. But we need to keep compatibility somehow. Maybe I should create a bundle extending the upcoming new bundle?

**Comment by willdurand** [comment]
Bazinga was my vendor name. The Bundle prefix was quite common in 2012 too ;-)

**Comment by Nyholm** [comment]
>  But we need to keep compatibility somehow. 

Do we? Im planning to release a major version of this bundle with all the changes from Geocoder. 

> The Bundle prefix was quite common in 2012 too ;-)

I do not mind it generally. But with Symfony 3.3 it is practice to use the namespace as service id.

**Comment by Nyholm** [comment]
Let's not rename it. "Bazinga" is cooler. =) 

Im happy with the current state of this PR.

**Pull request merged**
