### PR TITLE
Adding api_key for the YandexFactory

### PR DESCRIPTION
**Pull request by grulex**
Package geocoder-php/yandex-provider updated, we can use api_key for yandex-geocoder

### CODE REVIEW

**Comment by norkunas** [comment]
@grulex could you force push to trigger ci actions again to make it green? Because I can't merge otherwise

**Comment by grulex** [comment]
@norkunas It does not help

**Comment by norkunas** [comment]
Please try one more time, I've fixed CS.

**Comment by norkunas** [comment]
Also could you squash your commits? :)

**Comment by grulex** [comment]
@norkunas I delete two commits. Can you merge?

**Comment by norkunas** [comment]
@grulex now it's again complaining for CS. This should be fixed if you'll rebase your fork with upstream/master, but please don't introduce again unnecessary commits. While I'd like to merge this as is, I can't because I don't have permissions to merge PR's which doesn't pass the CI checks.

**Comment by grulex** [comment]
@norkunas complete

**Comment by norkunas** [comment]
Thank you @grulex

**Pull request merged**
