### PR TITLE
Allow configuring local IP when using FakeIpPlugin

### LINKED ISSUE #282: Allow faking other local ips, not just 127.0.0.1
I'm using symfony in a dockerized local environment using an older Docker setup on Windows, where it's using a VM. So my local IP is 192.168.99.1 and not 127.0.0.1

in `Resources\config\services.yml`:

```yaml
    Bazinga\GeocoderBundle\Plugin\FakeIpPlugin:
        class: Bazinga\GeocoderBundle\Plugin\FakeIpPlugin
        arguments: ['127.0.0.1', ~, false]
```

the local IP argument should be configurable for this case.

### PR DESCRIPTION
**Pull request by teo-sk**
Fixes #282

### CODE REVIEW

**Comment by norkunas** [comment]
Thank you, looks good. But I can't merge it because static analysis is red and I don't have greater permissions in this repo :/
ping @Nyholm

**Comment by Nyholm** [comment]
There are plenty of phpstan failures. I’m not sure if some are related or not. 

Let’s make an other PR to fix them, then rebase this PR when master is green

**Comment by norkunas** [comment]
#285 should unlock this

**Comment by norkunas** [comment]
@teo-sk could you rebase, please? :)

**Comment by teo-sk** [comment]
All green now :)

**Comment by norkunas** [comment]
Thank you @teo-sk :)

**Pull request merged**
