### PR TITLE
Upgrade to Geocoder V3

### PR DESCRIPTION
**Pull request by nicolassing**
I've not updated the documentation yet :/

### CODE REVIEW

**Comment by Baachi** [comment]
@nicolassing Great job! :+1: 
You have to set the php requirment to `>=5.4` and delete the php 5.3 build from the travis config file.

**Comment by nicolassing** [comment]
@Baachi thx :smiley:

**Comment by AntoineLemaire** [comment]
:+1:

**Comment by Baachi** [comment]
No Problem, @willdurand i think you can merge it, everythings looks good :)

**Comment by nicolassing** [comment]
I have to update the documentation to reflect some change. Maybe I'll have some time this week end :smile:

**Comment by jeremyFreeAgent** [comment]
Cool!

**Comment by willdurand** [comment]
Yay, merged!!!

**Comment by willdurand** [comment]
Thanks @nicolassing

**Comment by desmax** [comment]
Hint: cache of results has to be cleared after this update... :)

**Pull request merged**
